import {
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  XMarkIcon,
  CheckIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  XCircleIcon,
  CheckCircleIcon,
  EyeIcon,
  EyeSlashIcon,
  MagnifyingGlassIcon,
  PlusIcon,
  MinusIcon,
  PencilIcon,
  TrashIcon,
  Cog6ToothIcon,
  UserIcon,
  UsersIcon,
  BuildingOfficeIcon,
  DevicePhoneIcon,
  ComputerDesktopIcon,
  DeviceTabletIcon,
  CurrencyDollarIcon,
  CalendarIcon,
  ClockIcon,
  BellIcon,
  ShieldCheckIcon,
  ChartBarIcon,
  DocumentTextIcon,
  PrinterIcon,
  ArrowDownTrayIcon,
  HomeIcon,
  ArrowLeftIcon
} from '@heroicons/react/24/outline'

import {
  CheckIcon as CheckIconSolid,
  XMarkIcon as XMarkIconSolid,
  ExclamationTriangleIcon as ExclamationTriangleIconSolid,
  InformationCircleIcon as InformationCircleIconSolid,
  XCircleIcon as XCircleIconSolid,
  CheckCircleIcon as CheckCircleIconSolid
} from '@heroicons/react/24/solid'

// Export all icons for easy import
export {
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  XMarkIcon,
  CheckIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  XCircleIcon,
  CheckCircleIcon,
  EyeIcon,
  EyeSlashIcon,
  MagnifyingGlassIcon,
  PlusIcon,
  MinusIcon,
  PencilIcon,
  TrashIcon,
  Cog6ToothIcon,
  UserIcon,
  UsersIcon,
  BuildingOfficeIcon,
  DevicePhoneIcon,
  ComputerDesktopIcon,
  DeviceTabletIcon,
  CurrencyDollarIcon,
  CalendarIcon,
  ClockIcon,
  BellIcon,
  ShieldCheckIcon,
  ChartBarIcon,
  DocumentTextIcon,
  PrinterIcon,
  ArrowDownTrayIcon,
  HomeIcon,
  ArrowLeftIcon,
  CheckIconSolid,
  XMarkIconSolid,
  ExclamationTriangleIconSolid,
  InformationCircleIconSolid,
  XCircleIconSolid,
  CheckCircleIconSolid
}

// Create a mapping for easy reference
export const HeroIcons = {
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ChevronDown: ChevronDownIcon,
  ChevronUp: ChevronUpIcon,
  XMark: XMarkIcon,
  Check: CheckIcon,
  ExclamationTriangle: ExclamationTriangleIcon,
  InformationCircle: InformationCircleIcon,
  XCircle: XCircleIcon,
  CheckCircle: CheckCircleIcon,
  Eye: EyeIcon,
  EyeSlash: EyeSlashIcon,
  MagnifyingGlass: MagnifyingGlassIcon,
  Plus: PlusIcon,
  Minus: MinusIcon,
  Pencil: PencilIcon,
  Trash: TrashIcon,
  Cog6Tooth: Cog6ToothIcon,
  User: UserIcon,
  Users: UsersIcon,
  BuildingOffice: BuildingOfficeIcon,
  DevicePhone: DevicePhoneIcon,
  ComputerDesktop: ComputerDesktopIcon,
  DeviceTablet: DeviceTabletIcon,
  CurrencyDollar: CurrencyDollarIcon,
  Calendar: CalendarIcon,
  Clock: ClockIcon,
  Bell: BellIcon,
  ShieldCheck: ShieldCheckIcon,
  ChartBar: ChartBarIcon,
  DocumentText: DocumentTextIcon,
  Printer: PrinterIcon,
  ArrowDownTray: ArrowDownTrayIcon,
  Home: HomeIcon,
  ArrowLeft: ArrowLeftIcon
}